require './new_black_jack.rb'

new_game = BlackJack.new
new_game.create_array_of_deck_of_cards
new_game.get_players
new_game.assign_value_to_cards
new_game.deal_cards_to_players
new_game.display_cards
new_game.show_dealer_face_card
new_game.player_card_totals
new_game.display_total_for_players
new_game.deal_the_dealer_cards
new_game.hit_or_stay
new_game.show_dealer_second_card
new_game.hit_the_dealer
new_game.determine_winners
